modLoader="javafml"
loaderVersion="${loader_range}"
issueTrackerURL="https://github.com/progwml6/ironshulkerbox/issues"
license="GNU General Public License v3.0"

[[mods]]
    modId="ironshulkerbox"
    namespace="ironshulkerbox"
    version="${version}"
    displayName="Iron Shulker Boxes"
    authors="cpw, alexbegt, progwml6"
    description='''
New Shulker Boxes with larger sizes, with in-place upgrade items.
The feature shulker box is the crystal chest, which is transparent - some inventory contents are visible without opening the shulker box 
    '''
    displayURL="https://minecraft.curseforge.com/projects/iron-shulker-boxes"

[[dependencies.ironshulkerbox]]
    modId="forge"
    mandatory=true
    versionRange="${forge_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.ironshulkerbox]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_range}"
    ordering="NONE"
    side="BOTH"
